### ISSUE TITLE
orderui crash following last pull Origin

### ISSUE THREAD

**Issue by louisloio** [keuvinG/order-ui#3]
Hey @keuvinG ,

J'ai un bug avec le dernier commit que tu as fais, quand je lance le site j'ai ce message qui apparait.

![image](https://user-images.githubusercontent.com/29161010/102599040-d6925e00-4114-11eb-976e-614687e9f9f8.png)

je vais partir au spors la mais chaud pour qu'on regarde cette aprem

**Comment by keuvinG** [comment]
npm install (ou npm i)
