### ISSUE TITLE
productDetail - close page

### ISSUE THREAD

**Issue by louisloio** [keuvinG/order-ui#5]
click on cancel or dark area when it visible to close the page
![Screenshot 2020-12-18 at 17 57 31](https://user-images.githubusercontent.com/29161010/102645608-a077cd00-415a-11eb-9055-a19787378576.png)

also close/hide the page when I click on "add Basket
![Screenshot 2020-12-18 at 17 56 16](https://user-images.githubusercontent.com/29161010/102645419-5abb0480-415a-11eb-8419-ac10a90b50a7.png)
"

**Comment by keuvinG** [comment]
done sauf le black area click
