### ISSUE TITLE
productDetail - display one item after click

### ISSUE THREAD

**Issue by louisloio** [keuvinG/order-ui#6]
when I click on item 
then the productDetail appear

the product quantity is 0
I think we should automatically show one here 
![Screenshot 2020-12-18 at 18 01 25](https://user-images.githubusercontent.com/29161010/102646063-5511ee80-415b-11eb-9183-c4697e651c66.png)

like this the user has just to click on add to basket if he want one or cancel if he don't want.

**Comment by keuvinG** [comment]
done
